# Generated by Django 5.2.7 on 2026-03-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_target_possession_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usp',
            name='icon',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
