# Generated by Django 5.2.7 on 2026-04-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_usp_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='tax_included',
            field=models.BooleanField(default=False),
        ),
    ]
