# Generated by Django 5.2.7 on 2026-03-19 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_delete_rentalgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='rent.rentalproperty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
