# Generated by Django 5.2.7 on 2026-03-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_rentalgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalGallery',
        ),
    ]
