# Generated by Django 5.2.7 on 2026-03-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_setting_address_alter_setting_googletagmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='title',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='button_text',
        ),
        migrations.AddField(
            model_name='slider',
            name='headeing_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='search_btn_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='short_description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='tabs_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
