# Generated by Django 5.2.7 on 2026-03-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_title_slider_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='testmonial_bg',
        ),
        migrations.AddField(
            model_name='setting',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
