# Generated by Django 5.2.7 on 2026-03-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_setting_testmonial_bg_setting_hero_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, null=True),
        ),
    ]
