# Generated by Django 5.2.7 on 2026-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_service_image_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='services_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='services_hero',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='services_text',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
