# Generated by Django 5.2.7 on 2026-03-22 05:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_setting_services_description_setting_services_hero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='awards_recognitions',
        ),
        migrations.RemoveField(
            model_name='about',
            name='happy_families',
        ),
        migrations.RemoveField(
            model_name='about',
            name='highlight_icon_color',
        ),
        migrations.RemoveField(
            model_name='about',
            name='home_bg',
        ),
        migrations.RemoveField(
            model_name='about',
            name='looking_to_button_link',
        ),
        migrations.RemoveField(
            model_name='about',
            name='looking_to_button_text',
        ),
        migrations.RemoveField(
            model_name='about',
            name='looking_to_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='looking_to_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='projects_delivered',
        ),
        migrations.RemoveField(
            model_name='about',
            name='search_bg',
        ),
        migrations.RemoveField(
            model_name='about',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='about',
            name='who_we_are_description',
        ),
        migrations.RemoveField(
            model_name='about',
            name='who_we_are_subtitle',
        ),
        migrations.RemoveField(
            model_name='about',
            name='who_we_are_title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='years_of_excellence',
        ),
        migrations.AddField(
            model_name='about',
            name='bottom_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
