# Generated by Django 5.2.7 on 2026-03-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_about_awards_recognitions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='hero_video',
            field=models.URLField(blank=True, help_text='Paste YouTube Video Link', null=True),
        ),
    ]
