# Generated by Django 5.2.7 on 2026-03-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_setting_hero_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='hero_video',
        ),
    ]
