# Generated by Django 5.2.7 on 2026-03-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_setting_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='youtube_embed_id_hero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='YouTube Video ID'),
        ),
    ]
