# Generated by Django 5.2.7 on 2026-03-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_setting_youtube_embed_id_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='youtube_embed_id_hero',
        ),
    ]
