# Generated by Django 5.2.7 on 2026-04-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_setting_youtube_embed_id_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='why_choose',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='why_choose/'),
        ),
    ]
